version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tobacco_shop
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/ 